### ISSUE TITLE
Stream, not action, is being sent to reducers

### ISSUE THREAD

**Issue by gopowerrangers** [brianegan/dart_redux_epics#29]
Hi I am using the following code to sync to a Firebase real time database. After opening the Firebase stream, the Epic should send a new `CreateTodoListFromStrings` action to the reducers, which keeps the Redux TodoList synced with the database. 
![image](https://user-images.githubusercontent.com/36133393/57579075-f5ecf200-74c0-11e9-983a-402fc2021d62.png)

I thought it would be enough to just return on Observable (as is shown in examples here https://medium.com/shift-studio/flutter-redux-and-firebase-cloud-firestore-in-sync-2c1accabdac4) and it was resolved into an action by the time it reaches the reducer. Other examples, including this repo's ReadMe, are returning a stream or Observable, so I assumed this pattern would work.

But according to the debugger, the reducers are receiving the Observable itself. As a result none of the reducers are activated, and the store is never updated. 
![image](https://user-images.githubusercontent.com/36133393/57579225-685ed180-74c3-11e9-8b95-bce37536c836.png)

Am I not thinking about this the right way?

**Comment by gopowerrangers** [comment]
Resolved.

In the epic, I needed to remove the second `return` (before the `_getFirebaseTodoStrings`).

**Comment by gopowerrangers** [comment]
Never mind, it does not work, I was looking at the wrong thing. 

But I did force it work using the following code 
![image](https://user-images.githubusercontent.com/36133393/57921707-346f1c00-78c8-11e9-8679-582ae330fbb3.png)

Could someone explain why the code above works but not the code below? 
![image](https://user-images.githubusercontent.com/36133393/57921734-48b31900-78c8-11e9-9d9c-706e7d80ce0b.png)

**Comment by brianegan** [comment]
Hey there -- the first example returns a `Stream<CreateTodoListFromStrings>` -- therefore, the epic will dispatch `CreateTodoListFromStrings` received from that Stream. The second example returns a `Stream<Stream<CreateTodoListFromStrings>>`. Therefore, the epic will emit the inner `Stream<CreateTodoListFromStrings>`.

To "unwrap" the inner stream, instead of using `map`, use `flatMap`. For example: `.ofType().flatMap(...)`.

flatMap will subscribe to that inner Stream and emit the `CreateTodoListFromStrings` actions.

**Comment by gopowerrangers** [comment]
Yup that fixes it.
