### ISSUE TITLE
Epic `store.dispatch` workflow

### ISSUE THREAD

**Issue by NevRA** [brianegan/dart_redux_epics#3]
Hi
I have code (just example):
```
Stream<Object> _onSomeAction(Stream<Object> actions, EpicStore<AppState> store) {
    return actions.where((action) => action is SomeAction).asyncMap(
          (action) => _api.someAction()
              .then((result) => new AnotherAction()),
        );
  }
```

It works well if I want to handle **AnotherAction** only in reducers. But very often I want to handle this action in **another** Epic(s). For example:
```
Stream<Object> _onAnotherAction(Stream<Object> actions, EpicStore<AppState> store) {
    return actions.where((action) => action is AnotherAction).asyncMap(
          (action) => _api.anotherAction()
              .then((result) => new FinalAction()),
        );
  }
```

It will not work as is. To fix it I can merge streams from both Epics:
```
Stream<Object> _onSomeAction(Stream<Object> actions, EpicStore<AppState> store) {
    final stream = actions.where((action) => action is SomeAction).asyncMap(
          (action) => _api.someAction()
              .then((result) => new AnotherAction()),
        );

    return new MergeStream([stream, _onAnotherAction(stream, store)]);
  }
```
But IMHO it complicates the readability of the code and add additional complexity.
I tried to dispatch action directly from Epic:
```
Stream<Object> _onSomeAction(Stream<Object> actions, EpicStore<AppState> store) {
    return actions.where((action) => action is SomeAction).asyncMap(
          (action) => _api.someAction()
              .then((result) => dispatcher.dispatch(new AnotherAction())), // dispatcher - just a wrapper for store.dispatch
        );
  }
```
and it work like a charm! Now I can handle **AnotherAction** in reducers and in Epics.
But I found bellow comment in EpicStore sources:
```
/// Due to the way streams are implemented with Dart, it's impossible to
/// perform `store.dispatch` from within an [Epic] or observe the store directly.
```
if I understood correctly this comment solution with direct dispatch call should **not** work but it works.

That is why I have few questions:
1. What does this comment mean?
2. Can I continue to use dispatch in Epics without any undesirable consequences?
3. Why Epics doesn't support this scenario without any MergeStream by default?

Thanks!

**Comment by brianegan** [comment]
Hey, thanks for writing in! Interesting case :)

  1. The reason for my comment: The underlying `StreamController` is a `sync` stream. Due to some peculiarities in the way `sync` streams work, if the `dispatcher` function you provide is `sync` (as `store.dispatch` is), it will throw State errors when you try to use it.
2. If `dispatcher` function is `async`, you probably can? I haven't thoroughly tested it.
3. I decided to leave this functionality out because the authors of the original Epics library for JS have the following comment in their documentation: "Using store.dispatch() inside your Epic is an anti-pattern and will be removed in v1.0.0 of redux-observable so it's best not to use it." My guess is they used the pattern you describe and ran into issues, so I decided to follow their advice and leave it out of this lib as well.

Now, I don't 100% know your use case, but my thinking is thus: This library should be very simple and leave the tough stuff up to core language features or RxDart. Would you consider writing your function with the `async*` syntax more readable?

```dart
Stream _onSomeAction(Stream actions, EpicStore<AppState> store) async* {
  await for (dynamic action in actions) {
    if (action is SomeAction) {
      final result = await _api.someAction();
      yield new AnotherAction(result);
      yield new FinalAction(await _api.anotherAction(result));
    }
  }
}
```

**Comment by NevRA** [comment]
Hmmm )

1. Everything works fine. Do you have example when it doesn't?
2. We use it synchronously (no async or any async streams)
3. OK

I can't to execute your example successfully. It never gets inside **await for (dynamic action in actions)** block. (
Only way I made it work:
```dart
return actions
        .where((action) => action is SomeAction)
        .map((action) => action as SomeAction)
        .asyncExpand((action) async* {
      final result = await _api.someAction();
      yield new AnotherAction(result);
      yield new FinalAction(await _api.anotherAction(result));
  });
```

**Comment by brianegan** [comment]
Thanks so much for working through this with me!

1) Sure thing! I pushed up this branch: https://github.com/brianegan/dart_redux_epics/tree/state-error. I added a sync function called `dispatch` to the `EpicStore` that simply calls `_store.dispatch`. If you try to run the test suite, you'll see the "dispatches actions dos not work" test I added fails with a `Bad State` error.
2) Could you please provide a bit more code showing how you're providing the `dispatcher` to your epic? I'm a bit fuzzy on how exactly you're doing that, and it might provide a clue as to why it's working? :)
3) Hrm, you're right. That should "just work," but it appears that it doesn't. I'll need to dig into what's going wrong there. I'm on vacation with my family, so I'll take a deeper look once I'm back in action next week!

**Comment by NevRA** [comment]
1. Great! I'll test it and write you back.

**Comment by NevRA** [comment]
Thanks for the good example! I understand why it works in our case. 
It works for us because we use dispatch in asyncMap (we need Future -> Stream transformation), asyncMap  works **asynchronous** that is why we don't see problem. ))
Your example was very helpful and now we don't have any gaps.
Thanks for your work! Epics rocks!

**Comment by brianegan** [comment]
Woohoo! Totally makes sense now. I'll leave the issue open for now as a reminder to investigate the async* functions a bit more. 

Thanks for helping me understand and track it down. Glad it's working well for ya :)

**Comment by oqu** [comment]
What would be the right way to get an epic return several actions ?
The async* version looked promising but I only received one action and then, it seems it is blocked.

**Comment by brianegan** [comment]
@oqu Thanks for writing in! Busy busy, haven't quite had time to suss out exactly why `async*` functions aren't working whereas RxDart / normal Streams allow for this...

My recommendation: Use RxDart. Then, you have a couple of options:

Use `startWith`:

```dart
Stream<dynamic> startWithEpic(
  Stream<dynamic> actions,
  EpicStore<State> store,
) {
  return new Observable(actions)
      // Filter down to Request1 Actions
      .ofType(new TypeToken<PerformSearchAction>())
      .flatMap((action) {
        return new Observable.fromFuture(api
                .search(action.searchTerm)
                .then((results) => new SearchResultsAction(results))
                .catchError((error) => new SearchErrorAction(error)))
             // We'll use `StartWith` on the Inner Observable to emit an initial Action
             // when our API starts fetching.
            .startWith(new StartSearchAction());
  });
}
```

Use `new Observable.merge`. The types in here are just examples to give you an idea.

```dart
Stream<dynamic> fireTwoActionsEpic(
    Stream<dynamic> actions, EpicStore<List<dynamic>> store) {
  return new Observable(actions)
      // Filter down to Request1 Actions
      .ofType(new TypeToken<PerformSearchAction>())
      // Emit the items from a new Stream. StartSearchAction will be sent, then 
      // SearchResponse after a bit of time
      .flatMap((action) => new Observable.merge([
            new Observable.fromIterable(<dynamic>[new StartSearchAction()]),
            new Observable.timer(new SearchResponse(), new Duration(milliseconds: 5))
          ]));
}
```

**Comment by oqu** [comment]
Thanks @brianegan , got it to work using observable and async*.

```dart
Stream<dynamic> epic(Stream<dynamic> actions, EpicStore<State> store) {
  return new Observable(actions)
      .ofType(new TypeToken<ActionToHandle>())
      .flatMap((action) => new Observable(() async*{
    yield new TestAction(step: 1);
    yield new TestAction(step: 2);
    yield new TestAction(step: 3);
    yield new TestAction(step: 4);
  }() ));
}
```

**Comment by brianegan** [comment]
Nice! I'm pretty sure you can even drop the `new Observable` wrapper as well to make it even less code.

**Comment by ranquild** [comment]
@brianegan I have heavily used this library in production and I'd like to say that origin issue is very important to me. What I would to have it to pass stream of actions returned by epic to pipeline from the start when new action is created. In other words, Just like in JS version https://redux-observable.js.org/docs/basics/Epics.html:

```
// DO NOT DO THIS
const actionEpic = (action$) => action$; // creates infinite loop
```

Is there any change you can adjust dart redux_epics to work the same way?

**Comment by brianegan** [comment]
Hey @ranquild, thanks for writing in! Given the feedback, I think that's a fair suggestion. Instead of calling `next(action)` when you emit an action from an epic, I'll call `store.dispatch(action)` so it will go through your whole middleware chain, including epics. 

As you mention, this is actually what `redux_observable` does as well, but for some reason I thought they were just calling `next(action)` and that using `store.dispatch` was an anti-pattern from there docs. Reading more carefully, I still don't think we should allow folks to directly dispatch within the epic if the `redux_observable` community has found that to be an anti-pattern, but actions you emit from the epic should run through the entire chain.

As a heads up: That will mean the underlying Stream is no longer synchronous (I did this to make sync actions easier to work with, but in retrospect think it was a mistake). Therefore, if you're relying on the sync nature of this for now, you may see some bugs pop up.
